"""comment

Revision ID: 627f7f7a23d3
Revises: 9a5375bbf322
Create Date: 2024-02-02 14:16:30.857628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627f7f7a23d3'
down_revision = '9a5375bbf322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
