"""createman

Revision ID: 9a5375bbf322
Revises: c61821f7e4a6
Create Date: 2024-02-02 10:49:47.358830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5375bbf322'
down_revision = 'c61821f7e4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dateofbirth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dateofbirth',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
